[tools]
go = "1.26"
golangci-lint = "latest"

[tasks.run]
run = "go run -ldflags \"-X main.version=$(git describe --tags --always --dirty)\" ./cmd/debo"

[tasks.test]
run = "go test ./..."

[tasks.build]
run = "go build -ldflags \"-X main.version=$(git describe --tags --always --dirty)\" -o bin/debo ./cmd/debo"
